import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/common/Header";
import Sidebar from "@/components/common/Sidebar";
import Footer from "@/components/common/Footer";

import { Lexend_Deca } from "next/font/google";

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendDeca.className} antialiased flex flex-col h-screen`}
      >
        <Header />
        <div className="flex flex-1 h-[calc(100vh-80px)]">
          <Sidebar />
          <div className="flex-1 h-full w-full overflow-y-auto overflow-x-hidden max-md:pb-20">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
